using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace KrgWebAPI.Services
{
    public class PdfService
    {
        public byte[] GenerateInvoicePdf()
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Text("Invoice")
                        .FontSize(28)
                        .Bold()
                        .AlignCenter();

                    page.Content()
                        .Column(column =>
                        {
                            column.Spacing(10);

                            column.Item().Text("Customer: Demo Customer");
                            column.Item().Text("Invoice No: INV-001");
                            column.Item().Text($"Date: {DateTime.Now:dd-MM-yyyy}");

                            column.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Text("Product").Bold();
                                    header.Cell().Text("Qty").Bold();
                                    header.Cell().Text("Price").Bold();
                                });

                                table.Cell().Text("Laptop");
                                table.Cell().Text("1");
                                table.Cell().Text("80000");

                                table.Cell().Text("Mouse");
                                table.Cell().Text("2");
                                table.Cell().Text("1000");
                            });

                            column.Item().AlignRight().Text("Total: ₹82000").Bold();
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by KRG Billing System");
                });
            });

            return document.GeneratePdf();
        }
    }
}